//------------------------------------------------------------------------
// Copyright(c) 2023 Bobbo Studios.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"AutoVolumer.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"AutoVolumer VST3 (64Bit)"
#else
#define stringFileDescription	"AutoVolumer VST3"
#endif
#define stringCompanyName		"Bobbo Studios\0"
#define stringLegalCopyright	"Copyright(c) 2023 Bobbo Studios."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
